name: Test automation

on:
  push:
    branches:

jobs:
  tests:
    strategy:
      matrix:
        jdk:
          - 11
          - 17
          - 21
        clojure:
          - 1.10.3
          - 1.11.4
          - 1.12.0
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          java-version: "${{ matrix.jdk }}"
          distribution: temurin
          cache: maven
      - uses: delaguardo/setup-clojure@13
        with:
          lein: 2.11.2
      - name: Run tests
        run: lein with-profile clj${{ matrix.clojure }} test
